#!/usr/bin/env python3
import skilstak.colors as c
from time import sleep

for count in range(6):
    print(c.multi("Badger " + str(count)))
    sleep(0.4)

for count in range(2):  
    print(c.multi("Mushroom " + str(count)))
    sleep(0.4)         


